### PR TITLE
ci: Check if RBAC rules are in sync

### LINKED ISSUE #250: Keep RBAC rules in sync
Maybe somewhat related to #218.

We have several files with RBAC rules in the repository:

- `examples/rbac/rbac.yml`
- `helm/habitat-operator/templates/clusterrole.yaml`
- `test/e2e/v1beta1/resources/operator/cluster-role.yml`

Would be nice to keep them in sync. For example CI could fail if they are different in `rules` section for example.

### PR DESCRIPTION
**Pull request by krnowak**
Signed-off-by: Krzesimir Nowak <krzesimir@kinvolk.io>

Fixes #250.

### CODE REVIEW

**Comment by krnowak** [comment]
The failure will go away when #317 is merged.

File: hack/rbac-check.sh [hunk 1]
```diff
@@ -0,0 +1,80 @@
+#!/bin/bash
+
+set -euo pipefail
+
+dir=$(dirname "${BASH_SOURCE[0]}")
```
Comment (indradhanush) [inline hack/rbac-check.sh]: Nitpick: Marking this as `readonly` may be a good idea.

File: hack/rbac-check.sh [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+    path="${1}"
+    ignore=1
+    rules=()
+
+    while IFS="" read -r line || [[ -n "${line}" ]]
+    do
+        # strip the newline
+        line="${line%\\n}"
+        if [[ -z "${line}" ]]
```
Comment (indradhanush) [inline hack/rbac-check.sh]: Why have this check at all if you don't want to do anything here? :thinking:

File: hack/rbac-check.sh [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+example_path='examples/rbac/rbac.yml'
+chart_path='helm/habitat-operator/templates/clusterrole.yaml'
+test_path='test/e2e/v1beta1/resources/operator/cluster-role.yml'
+
+example_rules="$(read_rules "${dir}/../${example_path}")"
+chart_rules="$(read_rules "${dir}/../${chart_path}")"
+test_rules="$(read_rules "${dir}/../${test_path}")"
+
+# rely on transitivity, if example == chart and chart == test then
+# example == test
```
Comment (indradhanush) [inline hack/rbac-check.sh]: Just wanted to say that I like this. :smiley:

File: hack/rbac-check.sh [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+        line="${line%\\n}"
+        if [[ -z "${line}" ]]
+        then
+            # ignore empty lines
+            :
+        elif [[ "${line}" = 'rules:' ]]
+        then
+            # rules begin from the next line
+            ignore=0
+        elif [[ "${line}" =~ '{{' ]]
```
Comment (indradhanush) [inline hack/rbac-check.sh]: Same question here.

File: hack/rbac-check.sh (hunk 2 above)
Comment (krnowak) [reply hack/rbac-check.sh]: That prevents the code from other branches in the `if else` cascade to be executed. Did it that way to avoid adding yet another indentation level. There are several ways of doing that:

```
if [[ -z "${line}" ]]; then
  :
elsif …
then
  …
fi
```

or

```
if [[ -n "${line}" ]]; then
  if …
  then
    …
  fi
fi
```

or

```
if [[ -z "${line}" ]]; then
  continue # will work only if we are in a loop
fi
if …
then
  …
fi
```

File: hack/rbac-check.sh (hunk 1 above)
Comment (krnowak) [reply hack/rbac-check.sh]: Yeah, probably. Will do.

File: hack/rbac-check.sh (hunk 3 above)
Comment (krnowak) [reply hack/rbac-check.sh]: Was reading "Elements of programming" and "From mathematics to generic programming" so I guess they bent my brain a bit.

File: hack/rbac-check.sh (hunk 4 above)
Comment (krnowak) [reply hack/rbac-check.sh]: Same answer here. :P

**Comment by krnowak** [comment]
Updated and rebased on top of current master, so the test should pass now.
